{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ef02e3bb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8001/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [12/Mar/2024 15:06:17] \"GET /api/v1.0/2016-08-23/2016-10-23 HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [12/Mar/2024 15:06:55] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [12/Mar/2024 15:06:57] \"GET /api/v1.0/tobs HTTP/1.1\" 200 -\n",
      "[2024-03-12 15:07:00,262] ERROR in app: Exception on /api/v1.0/stations [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1719, in _execute_context\n",
      "    context = constructor(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1015, in _init_compiled\n",
      "    self.cursor = self.create_cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1386, in create_cursor\n",
      "    return self.create_default_cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1389, in create_default_cursor\n",
      "    return self._dbapi_connection.cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1083, in cursor\n",
      "    return self.dbapi_connection.cursor(*args, **kwargs)\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6229864448 and this is thread id 6246690816.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/var/folders/0_/sl5mx9ts48n8rm03l8w8sbj80000gq/T/ipykernel_28895/2205699001.py\", line 64, in stations\n",
      "    for row in station_data:\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/query.py\", line 2896, in __iter__\n",
      "    return self._iter().__iter__()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/query.py\", line 2903, in _iter\n",
      "    result = self.session.execute(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 1712, in execute\n",
      "    result = conn._execute_20(statement, params or {}, execution_options)\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1631, in _execute_20\n",
      "    return meth(self, args_10style, kwargs_10style, execution_options)\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/elements.py\", line 332, in _execute_on_connection\n",
      "    return connection._execute_clauseelement(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1498, in _execute_clauseelement\n",
      "    ret = self._execute_context(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1725, in _execute_context\n",
      "    self._handle_dbapi_exception(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 2043, in _handle_dbapi_exception\n",
      "    util.raise_(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/util/compat.py\", line 208, in raise_\n",
      "    raise exception\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1719, in _execute_context\n",
      "    context = constructor(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1015, in _init_compiled\n",
      "    self.cursor = self.create_cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1386, in create_cursor\n",
      "    return self.create_default_cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1389, in create_default_cursor\n",
      "    return self._dbapi_connection.cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1083, in cursor\n",
      "    return self.dbapi_connection.cursor(*args, **kwargs)\n",
      "sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6229864448 and this is thread id 6246690816.\n",
      "[SQL: SELECT measurement.station AS measurement_station \n",
      "FROM measurement GROUP BY measurement.station]\n",
      "[parameters: [{}]]\n",
      "(Background on this error at: https://sqlalche.me/e/14/f405)\n",
      "127.0.0.1 - - [12/Mar/2024 15:07:00] \"GET /api/v1.0/stations HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [12/Mar/2024 15:07:01] \"GET /api/v1.0/stations HTTP/1.1\" 200 -\n",
      "[2024-03-12 15:07:04,322] ERROR in app: Exception on /api/v1.0/precipitation [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1719, in _execute_context\n",
      "    context = constructor(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1015, in _init_compiled\n",
      "    self.cursor = self.create_cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1386, in create_cursor\n",
      "    return self.create_default_cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1389, in create_default_cursor\n",
      "    return self._dbapi_connection.cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1083, in cursor\n",
      "    return self.dbapi_connection.cursor(*args, **kwargs)\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6229864448 and this is thread id 6246690816.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/var/folders/0_/sl5mx9ts48n8rm03l8w8sbj80000gq/T/ipykernel_28895/2205699001.py\", line 52, in precipitation\n",
      "    prcp_data = session.query(Measurement.date,Measurement.prcp).filter(Measurement.date >= '2016-08-23').all()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/query.py\", line 2768, in all\n",
      "    return self._iter().all()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/query.py\", line 2903, in _iter\n",
      "    result = self.session.execute(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 1712, in execute\n",
      "    result = conn._execute_20(statement, params or {}, execution_options)\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1631, in _execute_20\n",
      "    return meth(self, args_10style, kwargs_10style, execution_options)\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/elements.py\", line 332, in _execute_on_connection\n",
      "    return connection._execute_clauseelement(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1498, in _execute_clauseelement\n",
      "    ret = self._execute_context(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1725, in _execute_context\n",
      "    self._handle_dbapi_exception(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 2043, in _handle_dbapi_exception\n",
      "    util.raise_(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/util/compat.py\", line 208, in raise_\n",
      "    raise exception\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1719, in _execute_context\n",
      "    context = constructor(\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1015, in _init_compiled\n",
      "    self.cursor = self.create_cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1386, in create_cursor\n",
      "    return self.create_default_cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 1389, in create_default_cursor\n",
      "    return self._dbapi_connection.cursor()\n",
      "  File \"/Users/samuelklein/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1083, in cursor\n",
      "    return self.dbapi_connection.cursor(*args, **kwargs)\n",
      "sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6229864448 and this is thread id 6246690816.\n",
      "[SQL: SELECT measurement.date AS measurement_date, measurement.prcp AS measurement_prcp \n",
      "FROM measurement \n",
      "WHERE measurement.date >= ?]\n",
      "[parameters: [{}]]\n",
      "(Background on this error at: https://sqlalche.me/e/14/f405)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [12/Mar/2024 15:07:04] \"GET /api/v1.0/precipitation HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [12/Mar/2024 15:07:05] \"GET /api/v1.0/precipitation HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "# Import the dependencies.\n",
    "from flask import Flask, jsonify\n",
    "import sqlalchemy\n",
    "from sqlalchemy.ext.automap import automap_base\n",
    "from sqlalchemy.orm import Session\n",
    "from sqlalchemy import create_engine, func\n",
    "\n",
    "#################################################\n",
    "# Database Setup\n",
    "#################################################\n",
    "engine = create_engine(\"sqlite:///Resources/hawaii.sqlite\")\n",
    "\n",
    "# reflect an existing database into a new model\n",
    "\n",
    "Base = automap_base()\n",
    "\n",
    "\n",
    "# reflect the tables\n",
    "Base.prepare(autoload_with=engine)\n",
    "\n",
    "\n",
    "# Save references to each table\n",
    "Measurement = Base.classes.measurement\n",
    "Station = Base.classes.station\n",
    "\n",
    "# Create our session (link) from Python to the DB\n",
    "session = Session(engine)\n",
    "\n",
    "#################################################\n",
    "# Flask Setup\n",
    "#################################################\n",
    "app = Flask(__name__)\n",
    "\n",
    "\n",
    "\n",
    "#################################################\n",
    "# Flask Routes\n",
    "#################################################\n",
    "@app.route(\"/\")\n",
    "def home():\n",
    "    return (\n",
    "        f\"Available Routes:<br/>\"\n",
    "        f\"<a href='/api/v1.0/precipitation'>/api/v1.0/precipitation</a><br/>\"\n",
    "        f\"<a href='/api/v1.0/stations'>/api/v1.0/stations</a><br/>\"\n",
    "        f\"<a href='/api/v1.0/tobs'>/api/v1.0/tobs</a><br/>\"\n",
    "        f\"/api/v1.0/*insert start date*<br/>\"\n",
    "        f\"/api/v1.0/*insert start date*/*insert end date* <br/>\"\n",
    "    )\n",
    "# Precipitation Route returns precpitation data from the last year recorded in the database\n",
    "@app.route(\"/api/v1.0/precipitation\")\n",
    "def precipitation():\n",
    "    prcp_data = session.query(Measurement.date,Measurement.prcp).filter(Measurement.date >= '2016-08-23').all()\n",
    "    prcp_dict = {}\n",
    "    for row in prcp_data:\n",
    "        prcp_dict[row[0]] = row[1]\n",
    "\n",
    "    return jsonify(prcp_dict)\n",
    "\n",
    "# Stations route returns JSON list of all stations in the database.\n",
    "@app.route(\"/api/v1.0/stations\")\n",
    "def stations():\n",
    "    station_data = session.query(Measurement.station).group_by(Measurement.station)\n",
    "    station_list = []\n",
    "    for row in station_data:\n",
    "        station_list.append(row[0])\n",
    "    return jsonify(station_list)\n",
    "\n",
    "# tobs route returns temp data from the most active station for the last year recorded in the database.\n",
    "@app.route(\"/api/v1.0/tobs\")\n",
    "def tobs():\n",
    "    temp_data = session.query(Measurement.date,Measurement.tobs).filter(Measurement.station == 'USC00519281').filter(Measurement.date >= '2016-08-23').all()\n",
    "    temp_dict = {}\n",
    "    for row in temp_data:\n",
    "        temp_dict[row[0]] = row[1]\n",
    "    return jsonify(temp_dict)\n",
    "\n",
    "#start route returns data that was recorded following the date in the url.\n",
    "\n",
    "@app.route(\"/api/v1.0/<start_date>\")\n",
    "def start_date(startdate):\n",
    "    data = session.query(Measurement.date,func.min(Measurement.tobs),func.max(Measurement.tobs),func.avg(Measurement.tobs)).group_by(Measurement.date).filter(Measurement.date >= start_date).all()\n",
    "    data_dict = {}\n",
    "    for row in data:\n",
    "        row_dict = {}\n",
    "        row_dict['min_temp'] = row[1]\n",
    "        row_dict['max_temp'] = row[2]\n",
    "        row_dict['avg_temp'] = row[3]\n",
    "       \n",
    "        data_dict[row[0]] = row_dict\n",
    "    return jsonify(data_dict)\n",
    "#start end date route returns data that was recorded within the range of dates in the url.\n",
    "@app.route(\"/api/v1.0/<start_date>/<end_date>\")\n",
    "def start_end_date(start_date,end_date):\n",
    "    data = session.query(Measurement.date,func.min(Measurement.tobs),func.max(Measurement.tobs),func.avg(Measurement.tobs)).group_by(Measurement.date).filter(Measurement.date >= start_date).filter(Measurement.date <= end_date).all()\n",
    "    data_dict = {}\n",
    "    for row in data:\n",
    "        row_dict = {}\n",
    "        row_dict['min_temp'] = row[1]\n",
    "        row_dict['max_temp'] = row[2]\n",
    "        row_dict['avg_temp'] = row[3]\n",
    "       \n",
    "        data_dict[row[0]] = row_dict\n",
    "    return jsonify(data_dict)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(debug=False)\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8e487e7a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
